Repository host-IT-Project/frontend, pull requests merged in 2022-11, with the labels that each got.

#14 추가: 캐러셀 컴포넌트 생성
  package-lock.json
  package.json
  src/components/BannerCarousel.jsx
Labels: ✨Feat, ⚠invalid, 🐛bug

#19 추가: 프로젝트 업로드 form 컴포넌트 생성
  src/components/UploadForm.jsx
  src/styles/style.js
Labels: ✨Feat

#20 추가: 검색 기능 구현
  package-lock.json
  package.json
  src/api/APITest.jsx
  src/api/article.js
  src/api/http.js
  src/components/ProductCardList.jsx
  src/components/search/OptionSearch.jsx
  src/components/search/SearchForm.jsx
  src/pages/ArchivePage.jsx
  src/pages/HomePage.jsx
  src/template/PageTemplate.jsx
  src/util/type.js
Labels: ✨Feat

#21 수정: 프로젝트 업로드 form의 textfield를 TUI Editor로 변경
  package-lock.json
  package.json
  src/components/UploadForm.jsx
Labels: ✨Feat, ⚒fix

#23 수정: 페이지 템플릿 높이 제한 조정 및 ContentWrapper 추가
  src/template/PageTemplate.jsx
Labels: ⚒fix

#29 추가: ProjectDetailPage UI 작업
  package-lock.json
  package.json
  src/components/ProjectInfoBox.jsx
  src/components/TextEditor.jsx
  src/components/TextViewer.jsx
  src/pages/ProjectDetailPage.jsx
  src/pages/Routes.jsx
Labels: ✨Feat

#31 추가: 작품 상세페이지 스타일 수정 및 작품 목록으로 돌아가기 버튼 추가
  src/components/ProjectInfoBox.jsx
  src/pages/ProjectDetailPage.jsx
  src/styles/style.js
  src/styles/theme.js
Labels: ⚒fix

#34 추가: getArticle API 추가
  src/api/APITest.jsx
  src/api/article.js
Labels: ✨Feat, 🚨Priority High

#38 수정: 작품 상세페이지 비동기 article 정보 조건부 렌더링 처리
  src/pages/ProjectDetailPage.jsx
Labels: 🐛bug, ⚒fix

#42 추가: 작품편집 페이지 등록/수정 요청 관련 함수 작성
  src/components/EditForm.jsx
Labels: ✨Feat, 🚨Priority High

#47 수정: CRUD API 수정
  src/api/APITest.jsx
  src/api/article.js
  src/api/http.js
  src/components/ProductCardHoriz.jsx
  src/components/ProjectInfoBox.jsx
  src/pages/MyPage.jsx
Labels: ✨Feat, ⚒fix

#49 수정: 썸네일 이미지 반영 및 UI 디테일 수정
  src/components/EditForm.jsx
  src/components/ProductCard.jsx
  src/components/ProductCardHoriz.jsx
  src/components/ProductCardList.jsx
  src/components/ProjectInfoBox.jsx
  src/components/TagInput.jsx
  src/pages/ProjectDetailPage.jsx
Labels: ✨Feat, ⚒fix
